spring:
  application:
    name: Wrm
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8083

scheduling:
  algorithms:
    fifo:
      name: "First In First Out"
      description: "Simple queue-based algorithm"
    priority:
      name: "Priority Based"
      description: "Schedule based on priority"
      priority-factors:
        - "urgency"
        - "waiting-time"
        - "severity"
    shortest-job-first:
      name: "Shortest Job First"
      description: "Schedule based on estimated duration"

  schedules:
    - weekday: "MONDAY"
      opening-time: "08:00"
      closing-time: "17:00"
    - weekday: "TUESDAY"
      opening-time: "08:30"
      closing-time: "16:30"
    - weekday: "WEDNESDAY"
      opening-time: "09:00"
      closing-time: "18:00"

  capacities:
    - weekday: "MONDAY"
      maxCapacity: 50
    - weekday: "TUESDAY"
      maxCapacity: 60
    - weekday: "WEDNESDAY"
      maxCapacity: 45
