spring:
  application:
    name: Wrm
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081
scheduling:
  algorithms:
    fifo:
      name: "First In First Out"
      description: "Simple queue based algorithm"
    priority:
      name: "Priority Based"
      description: "Schedule based on priority"
      priority-factors:
        - "urgency"
        - "waiting-time"
        - "severity"
    shortest-job-first:
      name: "Shortest Job First"
      description: "Schedule based on estimated duration"

  schedules:
    - weekday: MONDAY
      openingTime: 08:00
      closingTime: 17:00
    - weekday: TUESDAY
      openingTime: 08:30
      closingTime: 16:30
    - weekday: WEDNESDAY
      openingTime: 09:00
      closingTime: 18:00

  capacities:
    - weekday: MONDAY
      maxCapacity: 50
    - weekday: TUESDAY
      maxCapacity: 60
    - weekday: WEDNESDAY
      maxCapacity: 45